# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_auto_20181113_2108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedata',
            options={'verbose_name': 'Image Example', 'verbose_name_plural': 'Image Examples'},
        ),
        migrations.AddField(
            model_name='imagedata',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height'),
        ),
        migrations.AddField(
            model_name='imagedata',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=80, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagedata',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width'),
        ),
        migrations.AlterField(
            model_name='imagedata',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
    ]
