# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_auto_20181201_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedata',
            options={'verbose_name': 'Image Example', 'verbose_name_plural': 'Image Examples'},
        ),
        migrations.RemoveField(
            model_name='imagedata',
            name='sort_order',
        ),
    ]
