# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-02 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_auto_20181201_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='images',
            field=models.ManyToManyField(through='product.VariantImage', to='product.ImageData'),
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_images', to='product.ImageData'),
        ),
    ]
